services:
  - type: web
    name: restroom-final
    env: node
    buildCommand: cd restroom-final/frontend && yarn install && yarn build
    startCommand: serve -s restroom-final/frontend/build
    plan: free
